name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.0, 7.1, 7.2, 7.3, 7.4]
        phpunit: [6.5.13, 7.5.18]

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          php_version: ${{ matrix.php }}
          version: ${{ matrix.phpunit }}
