name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        phpunit: [9.5.26, 10.5.38, 11.4.3]
        php: [8.2, 8.3]

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6.1.1
        with:
          php_version: ${{ matrix.php }}

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3.0.2
        with:
          php_version: ${{ matrix.php }}
          version: ${{ matrix.phpunit }}
